### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by TechDudie** [pl608/EBook-Downloader#1]
I need more info if i can resolve issue

Ik getstuff is called in run but where is run called? (downloadC.py)

**Comment by pl608** [comment]
`download.py` is used as a module in `main-gui.pyw` and `downloadC.py` is used in the same way in `main-console.py`(C for console)

**Comment by pl608** [comment]
same for strip.py and stripC.py

**Comment by pl608** [comment]
also the present problem is that for some reason python is saying that an array doesn't have something i'm pretty darn sure it has

**Comment by pl608** [comment]
also figured out issue. cant remember the problem atm, but it was pretty dumb
